### ISSUE TITLE
About Horiozn and Avia in the dataset of chaotic points

### ISSUE THREAD

**Issue by zhSlamer** [TIERS/multi-lidar-dataset#13]
**1. In forest01_st_square_2022-02-08-23-14-55bag, in the beginnig and at 53s , why are there so many chaotic points?Or what materials are responsible for it, Glass or something else?**
horizon scan points picture:
![forest01_horizon_53s](https://user-images.githubusercontent.com/68368006/222937830-5548b128-f536-4897-b3e4-f2ff447e5db0.png)
avia scan points picture:
![forest01_avia_53s](https://user-images.githubusercontent.com/68368006/222937835-237789dd-8b04-43b8-ac10-50a402a09b32.png)

**Comment by QingKe-UP** [comment]
I think these are “sunlight noise”, and the same noise has also appeared in my own dataset. The fifth section of this webpage describes this issue. 【 https://www.livoxtech.com/cn/showcase/livox-tag 】
